[package]
name = "tida"
version = "0.0.0"
description = "Threat Intelligence Desktop Assistant"
authors = ["Ali0th"]
license = "GPLv3"
repository = "https://github.com/martin2877/tida"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
serde_json = "1.0"
tauri = { version = "1.4", features = [ "updater", "clipboard-all", "dialog-open", "fs-read-file", "global-shortcut-all", "http-all", "http-multipart", "notification", "notification-all", "path-all", "protocol-asset", "shell-open", "system-tray", "window-all"] }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
screenshots = {git = "https://github.com/pot-app/screenshots-rs"}
selection = {git = "https://github.com/pot-app/Selection"}
tiny_http = "0.12.0"
once_cell = "1.17.1"
toml = "0.7.3"
serde = "1.0.159"
dirs = "5.0.0"
dunce = "1.0.4"
image = "0.24.6"
base64 = "0.21.2"

[target.'cfg(windows)'.dependencies]
windows = {version="0.44.0",features= ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }
window-shadows = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
window-shadows = "0.2"
core-graphics = "0.22.3"
macos-accessibility-client = "0.0.1"

[target.'cfg(target_os = "linux")'.dependencies]
mouse_position = "0.1.3"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
